sub_themes_dict={0: '"Turn Display Off After X Mins" Not working',
 1: 'Adapter gets hot',
 2: 'Ads interupts device use',
 3: 'Alexa integration - Device pairing',
 4: 'Alexa-related issue',
 5: 'App crashing/glitching',
 6: 'App not working as expected',
 7: 'Apps not loading as expected',
 8: 'Arrived Defective',
 9: 'Backup and Restore did not work',
 10: 'Bluetooth constantly disconnects',
 11: 'Buttons clicking itself',
 12: "Can't block app purchase",
 13: "Charging Cable won't fit",
 14: "Charging Cable won't stay plugged in",
 15: 'Dead pixel on screen',
 16: 'Delivery Related',
 17: 'Device already registered',
 18: 'Device heats up',
 19: 'Device needs to be plugged to use',
 20: 'Device not charging',
 21: 'Device not holding charge',
 22: 'Device not turning on',
 23: 'Device stuck on homescreen',
 24: 'Devices shuts down constantly',
 25: 'Does not support Hoopla App',
 26: 'Feedback - Battery life not adequate',
 27: 'Feedback - Camera',
 28: 'Feedback - Competitor comparision',
 29: 'Feedback - Device too small',
 30: 'Feedback - Difficult to setup',
 31: 'Feedback - Difficult to use',
 32: 'Feedback - Heavy to hold',
 33: 'Feedback - Keyboard related',
 34: 'Feedback - Lockscreen ads',
 35: 'Feedback - Needs more RAM',
 36: 'Feedback - Power button',
 37: 'Feedback - Sound quality',
 38: 'Feedback - Storage',
 39: 'Feedback - Wireless Charging',
 40: 'General - Did not meet expectations',
 41: 'Incompatible with prior-gen accessories',
 42: 'Issue with charging port',
 43: 'Item arrived Damaged',
 44: 'Item arrived late',
 45: 'Item arrived missing',
 46: 'Item not in packaging',
 47: 'Language missing',
 48: 'Lines on screen',
 49: 'Lockscreen ads not removed after purchase',
 50: 'Mail app not working',
 51: 'Missing hyperlink Kindle feature',
 52: 'Missing navigation icons',
 53: 'Missing power cable',
 54: 'Moisture Detection Issue',
 55: 'Need Detailed Owners Manual',
 56: 'No Reason Given',
 57: 'Not able to download apps',
 58: 'Not able to exchange',
 59: 'Not able to log out of Amazon App',
 60: 'Not able to register',
 61: 'Not able to setup Teen profile',
 62: 'Not able to sideload Apps',
 63: 'Not able to use device without wifi',
 64: 'Not able to verify Amazon account',
 65: 'Not compatible with BT device',
 66: 'Not easy to remove lockscreen Ads',
 67: 'On-screen Keyboard missing',
 68: 'Order not meet expectations',
 69: 'Parental controls do not work',
 70: 'Privacy concerns',
 71: 'Protective covers related',
 72: 'Red line appeared on screen',
 73: 'Refurb received not adequate',
 74: 'Refurb return process',
 75: 'Return-related Issue',
 76: 'SD Card not compatible',
 77: 'SD Card transfering files',
 78: "SD Card won't stay inserted into device",
 79: 'SD card reformat pop-up issue',
 80: 'Screen became blurry',
 81: 'Screen changing colors',
 82: 'Screen cracked',
 83: 'Screen dimming intermittently',
 84: 'Screen just flashes',
 85: 'Screen looks faded and washed out',
 86: 'Screen mirroring not working',
 87: 'Screen not responsive',
 88: 'Screen not working',
 89: 'Search experience related',
 90: 'Silk browser experience related',
 91: 'Sleep/Wake Cover not working',
 92: 'Slow/Sluggish Performance',
 93: 'Status sound / Volume fades out',
 94: 'Subscriptions not downloading',
 95: 'Trade-in Related',
 96: 'Unable to connect to Wi-Fi',
 97: 'Unable to connect to server (Internet-enabled Apps)',
 98: 'Unable to create profile for other user',
 99: 'Unable to download the apps I wanted',
 100: 'Unable to remove Amazon apps',
 101: 'Unable to see downloaded Apps on home screen',
 102: 'Unable to set weather to my location',
 103: 'Unable to sync device with existing profile',
 104: 'Unable to use Fire TV App',
 105: 'Unhappy with pre-installed Apps',
 106: 'Voice over accessibility feature request',
 107: 'Warranty-related issue',
 108: 'Wi-Fi slow/buffering',
 109: 'Wi-Fi using data in background',
 110: 'Wi-fi Disconnecting and Reconnecting',
 111: 'Word suggestions related',
 112: 'device gets hot',
 113: 'unknown'}